---
- name: Installing and Creating LAMP Stack Docker Contaianer
  hosts: workstation
  gather_facts: no
  
  tasks:
  - name: Update Repository Index
    apt:
      update_cache: yes


  roles:
  - container
  - LAMP
