---
# tasks file for LAMP
- name: Start Docker Service
  service:
    name: Docker
    state: started
    enabled: yes

- name: Install apache and php image
  docker_image:
    name: romeoz/docker-apache-php
    state: present
    source: pull

- name: Install mysql
  docker_image:
    name: mysql/msql-sercice
    state: present
    source: pull

